# fly.toml app configuration file generated for good-notes on 2023-10-16T19:44:26-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "good-notes"
primary_region = "dfw"

[build]

[env]
  PORT = "3001" # the port your app listens on

[http_service]
  internal_port = 3001 # the port your app listens on
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
